### ISSUE TITLE
lpinfo: success timeout on lpinfo -m

### ISSUE THREAD

**Issue by FrancYescO** [SickHub/docker-cups-airprint#33]
i've runned the container on a slow host, and it was failing to setup the printer as the list of driver was not shown..

with more debugging i've found that the `lpinfo -m` command was returning (after a while of loading...) just `lpinfo: success` deleting some folder from /usr/lib/cups/driver/ (no matther what folder) allowed me to fix the  `lpinfo -m` command, so basically was a timeout problem listing all installed drivers, stripping out some folder allow you to success... you probably should consider finding a way to enlarge this timeout (i assume the default is 30sec)

**Comment by DrPsychick** [comment]
The `lpinfo` command should only be needed initially to figure out what model you want to setup during start, so you would execute it manually.

Since you run it manually, you can use the option `--timeout <seconds>` to increase the timeout.

Does this answer your question @FrancYescO ?

**Comment by FrancYescO** [comment]
I runned manually for debug reasons, the main issue is that you cannot use the webui to configure a printer

**Comment by DrPsychick** [comment]
Ok, I'll close this then. External access is handled in #32

**Comment by FrancYescO** [comment]
Sorry probably you misunderstand, what i was saying is that due to this timeout, you cannot select the driver to use from the webinterface (the lpinfo: success error messagge is also shown on the webinterface) it's just a different thing from #32

**Comment by DrPsychick** [comment]
Ok, in that case, if cups itself is using `lpinfo`, there is not much I can do about that.

From what I read, it's one of the drivers that causes the problem. Maybe this thread will help you pin down the issue or even solve it: https://unix.stackexchange.com/questions/276736/cups-adding-printer-fails-with-unable-to-get-list-of-printer-drivers-success

**Comment by FrancYescO** [comment]
nope as said in the OP already checked if the culprit was a single driver, but is not the case.

it's just a timeout that can happens on some host due to the fact that all drivers are embedded and it can require some time for listing

**Comment by DrPsychick** [comment]
Alright, then we must figure out how to increase this timeout - within cups / web UI.

**Comment by DrPsychick** [comment]
If you run `lpinfo` manually, adding the flag `--timeout <seconds>` is the solution.

But for the web interface, I have no idea if it uses `lpinfo` and if, where that would be configurable.

**Comment by DrPsychick** [comment]
Closing as "gone cold"
