### ISSUE TITLE
Slow to collect information about printer and a lot more after reboot.

### ISSUE THREAD

**Issue by enzofrnt** [SickHub/docker-cups-airprint#55]
Hi,
I'm using docker on Synology NAS with OS names DSM based on busybox.

Looks like there is some issue in my log :
![image](https://user-images.githubusercontent.com/63660254/202849363-3542ef03-35cc-431d-9673-3ebd63b60154.png)

The default configuration of my printer :
![image](https://user-images.githubusercontent.com/63660254/202849388-e5b25e28-3820-4eac-8607-9dbf2776365a.png)

it takes a will to collect it collect the wrong things :
![IMG_0327](https://user-images.githubusercontent.com/63660254/202849447-701cde11-c9d0-4fc6-8cc9-2cb3fdd41bce.PNG)
![IMG_0326](https://user-images.githubusercontent.com/63660254/202849457-87796878-56fd-4a7e-b75f-47cc2ff6dd41.PNG)
Enveloppe <> A4

I don't understand what is going on, but I'm trying to find a solution. 
I will update if I have any more information.

**Comment by DrPsychick** [comment]
So a fix for those "Bad listen address" is incoming, however that should not affect operations as the bad config line is ignored.

**Comment by DrPsychick** [comment]
The problem about avahi not running is addressed by this snipped. It seems to die sometimes, so this makes sure it's started regularly:

```
# ensure avahi is running in background (but not as daemon as this implies syslog)
(
while (true); do
  /usr/sbin/avahi-daemon -c || { /usr/sbin/avahi-daemon & }
  sleep 5
done
) &
```

Feel free to do tests and let me know the outcome. Help to improve this is always appreciated!

**Comment by DrPsychick** [comment]
@enzofrnt is your problem solved? Then I would close this issue.

**Comment by DrPsychick** [comment]
Closing as "gone cold"
