### ISSUE TITLE
http https version cups mismatch

### ISSUE THREAD

**Issue by gertcuykens** [SickHub/docker-cups-airprint#73]
Hi, the http page shows OpenPrinting CUPS 2.4.2
https page shows OpenPrinting CUPS 2.4.1

**Comment by DrPsychick** [comment]
That is interesting, however I fear this is out of our control. Both are served from the same installation of CUPS. There are newer versions of CUPS that may have fixed this issue, but not yet available in Ubuntu 22.04.

**Comment by DrPsychick** [comment]
Closing as "gone cold"
