### ISSUE TITLE
"Bad Request" - Help configuring

### ISSUE THREAD

**Issue by Happylama25** [SickHub/docker-cups-airprint#74]
Hi! 

I'm trying to configure this for my printer, from what I read I need to first do cups-setup and configure everything, then copy the config, and create another container and copy the config to it, I'm still on the cups-setup, when I navigate to `localhost:631` I get a "Bad Request" message, I read on a stackoverflow issue that I should change Listen to *:631 but when looking at the config its got Listen /run/cups/cup.sock so I'm not sure if I should change that.

The IP it shows in the console didn't work for me, and neither does the hostname.

I have not setup anything like this before so I'm very newbie (and its also printers, so its always a hassle)

**Comment by DrPsychick** [comment]
Easiest way to configure the container or cups is by defining ENV variables

```
CUPS_REMOTE_ADMIN=${CUPS_REMOTE_ADMIN:-"yes"} # allow admin from non local source (sets *:631)
CUPS_IP=${CUPS_IP:-$(hostname -i)} # no need to set this usually
CUPS_HOSTNAME=${CUPS_HOSTNAME:-$(hostname -f)} # no need to set this usually -> allows accessing cups via name: https://cups.domain:631/
```

**Comment by DrPsychick** [comment]
@Happylama25 does this solve your issue?

**Comment by Happylama25** [comment]
Yes, apologies.

Thank you!
